### ISSUE TITLE
Can 'base_url' be customized to call deepseek from third-party websites?

### ISSUE THREAD

**Issue by mhaas6** [Tabing010102/DeepSeekTranslate#1]
For example, the website 'siliconflow.cn' offers new users a 14 yuan trial bonus and charges only ￥1.33 / M tokens for model usage, which is cheaper than the official website price. Alternatively, there are other intermediate prices and discounts available on various platforms.

Issue encountered 1:
I tried changing the Default Value: 'https://api.deepseek.com/chat/completions' to my own intermediary site such as 'https://xxxxx.com' or 'https://xxxxx.com/v1', but it did not take effect.
Issue encountered 2:
The configuration file does not support custom model names. For example, changing 'siliconflow.cn' from 'deepseek-chat' to 'deepseek-ai/DeepSeek-V2.5' prevents me from correctly calling the 'deepseek-chat' model.

**Comment by Tabing010102** [comment]
- For issue 1:
  - Perhaps you need to set Endpoint to full url of the completion api, i.e. `https://xxxxx.com/chat/completions` or `https://xxxxx.com/v1/chat/completions`
- For issue 2:
  - Added model settings in release v0.1.4, [link](https://github.com/Tabing010102/DeepSeekTranslate/releases/tag/v0.1.4)
![image](https://github.com/user-attachments/assets/830afc28-061d-4f54-82e6-14269794e10c)

**Comment by mhaas6** [comment]
Thank you, the software is functioning properly now.

However, I noticed that after enabling 'BatchTranslate', the translation process tends to get stuck easily. When it's turned off, everything works normally and there's no impact on usage. During my testing, I used the 'siliconflow.cn' API.

**Comment by Tabing010102** [comment]
> Thank you, the software is functioning properly now.
> 
> However, I noticed that after enabling 'BatchTranslate', the translation process tends to get stuck easily. When it's turned off, everything works normally and there's no impact on usage. During my testing, I used the 'siliconflow.cn' API.

- My prompt engineering is poor, so I copied prompt from [AiNiee](https://github.com/NEKOparapa/AiNiee), which is about 300 tokens. If I can find a shorter, stable and censorship-resistant prompt, the response time will be shorter.
- When `MaxTranslationsPerRequest` is 5, the official API response time is usually 5-10 seconds, which is indeed relatively slow.
Certain text may cause model degradation, which results in long response times and response text that repeats one character. Detection has not been implemented yet. So if you encounter problems, you may only be able to turn off BatchTranslate for better experience.
Besides, DeepSeek sometimes refuses to translate some NSFW content due to censorship, which will also cause the translation to fail.
- Current implementation splits text by line, which may cause misplaced text and translation failures. Its removal is planned.
